version: "3.7"

services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - 3080:3080
    environment:
      - PORT=3080
      - MONGODB_URL=mongodb://mongo:27017

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 4080:80
    environment:
      - PORT=80
