version: "3.7"

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js

  backend:
    build: ./backend
    restart: always
    ports:
      - 3080:80
      - 3443:443

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 4080:80
      - 4443:443
